# Generated by Django 5.2.6 on 2026-09-05 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('office_code', models.CharField(db_index=True, max_length=100)),
                ('website_code', models.CharField(db_index=True, max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('purchase_price', models.FloatField(default=0)),
                ('sale_price', models.FloatField(default=0)),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=200)),
                ('purchase_date', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('purchase_type', models.CharField(default='person', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['brand'], name='products_brand_b2547a_idx'), models.Index(fields=['-id'], name='products_id_9220dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_name', models.CharField(max_length=200)),
                ('watch_code', models.CharField(blank=True, default='', max_length=100)),
                ('issue', models.TextField(blank=True, default='')),
                ('delivery_date', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('return_date', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_warranty', models.BooleanField(default=False)),
                ('status', models.CharField(db_index=True, default='received', max_length=20)),
                ('repair_price', models.FloatField(default=0)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'repairs',
                'indexes': [models.Index(fields=['status', '-id'], name='repairs_status_6a756c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.FloatField(default=0)),
                ('purchase_price', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('sale_date', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('customer', models.CharField(blank=True, default='', max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('sale_type', models.CharField(default='person', max_length=20)),
                ('payment_type', models.CharField(default='cash', max_length=20)),
                ('final_price', models.FloatField(default=0)),
                ('paid_cash', models.FloatField(default=0)),
                ('paid_pos', models.FloatField(default=0)),
                ('paid_card2card', models.FloatField(default=0)),
                ('is_settled', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.product')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('total_amount', models.FloatField(default=0)),
                ('paid_amount', models.FloatField(default=0)),
                ('pay_date', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='inventory.product')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.sale')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(db_index=True, default='new', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tracking',
                'indexes': [models.Index(fields=['status', '-id'], name='tracking_status_51c35f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-sale_date', '-id'], name='sales_sale_da_e20aad_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_type', 'is_settled'], name='sales_payment_dc2d79_idx'),
        ),
    ]
