# Generated by Django 5.2.6 on 2026-09-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_store_name_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
